---
- name: Add nginx ingress controller helm repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  run_once: true

- name: Install ingress-nginx Chart
  kubernetes.core.helm:
    name: ingress-nginx
    namespace: ingress-nginx
    create_namespace: true
    chart_ref: ingress-nginx/ingress-nginx
    values: 
      controller:
        admissionWebhooks:
          enabled: false
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        service:
          type: ""
        kind: DaemonSet
  run_once: true
